import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const faviconVersion = "v1.2"; // Declare it here

export const metadata: Metadata = {
  title: {
    template: "%s | Neonova LLC",
    default: "Neonova LLC",
  },
  description:
    "Neonova LLC transforms content and strategy into immersive digital experiences — offering E-books & Publications, Digital Marketing, Software Development, and IT Solutions that engage, inspire, and scale.",
  icons: {
    icon: [
      `/assets/logo/neonova-logo.png?v=${faviconVersion}`,
      "/favicon.ico",
      // { url: "/assets/logo/fix-zone-2.png" },
    ],
  },
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />
        <div className="w-full bg-[#0A0B0D] border-t border-neutral-800/60 px-4 py-5">
          <p className="mx-auto max-w-5xl text-center text-[11px] sm:text-xs leading-relaxed text-neutral-500">
            <span className="font-semibold text-neutral-400">Disclaimer:</span>{" "}
            Elite Book Writers is owned by Neo Novallc LLC and operates as an
            independent organisation and has no affiliation, partnership,
            sponsorship, or association with any other company or brand that may
            share a similar or identical name. This includes, but is not limited
            to, well-known publishing companies or corporations. All content,
            services, and products available on this website are exclusively
            provided by Elite Book Writers and are not authorised, endorsed, or
            approved by any third party. All trademarks are the property of
            their respective owners.
          </p>
        </div>
      </body>
    </html>
  );
}
